name: Update port tracker
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths: ['syslog-ng/conf.d/integrations/**']

jobs:
  update-port-tracker:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: write
      
    steps:
    - name: Git Clone current repository
      uses: actions/checkout@v3
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Run extraction script
      run: |
        pip3 install pandas
        pip3 install tabulate
        python3 scripts/gha.py

    - name: Check for changes in git
      run: |
        if git diff --quiet; then
          echo "No changes found, skipping commit step."
          echo "status=none" >> $GITHUB_ENV
        fi

    - name: Commit/Push changes if found
      if: env.status != 'none'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git commit -a -m "Auto-update README"
        git push